[package]
name = "wireless-regdb"
version = "0.1.0"
authors = ["Finn Behrens <me@kloenk.de>"]
edition = "2018"
repository = "https://github.com/nyantec/wireless-regdb"
license = "MirOS"
keywords = [ "linux", "wireless", "wireless-regulatory" ]
categories = [ "internationalization", "os::linux-apis", "parsing" ]
description = "create a linux wireless regulatory db firmware"
homepage = "https://github.com/nyantec/wireless-regdb"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ ]
sign = [ "openssl" ]

[[example]]
name = "generate-regdb"

[dependencies]
anyhow = "1"
byteorder = "1.3"

openssl = { version = "0.10", optional = true }
